### ISSUE TITLE
CSV Upload / Mapping Abstraction

### ISSUE THREAD

**Issue by andyslack** [juicyllama/framework#18]
Building on both:

https://github.com/juicyllama-npm/core/issues/91
https://github.com/juicyllama-npm/core/issues/94

We are looking to create a similar abstraction layer for CSV importing. Allowing charting endpoints to be easily implemented across our framework.

This task will need:

A crudUploadCSVFile function similar to the others here https://github.com/juicyllama-npm/core/blob/main/src/helpers/crudController.ts#L47 plus the abstracted service alongside.

The accompanying decorator helper similar to this one https://github.com/juicyllama-npm/core/blob/main/src/decorators/crud.decorator.ts#L75

The testing endpoint for automated testing of the new controller here - https://github.com/juicyllama-npm/core/blob/main/src/test/helpers.ts

The controller should support the following:

file: A CSV file upload, you can see how we do this for avatars (also abstracted here): https://github.com/juicyllama-npm/core/blob/main/src/modules/users/users.controller.ts#L125
mappers: string[]
skip_first: boolean (if to ignore the first row)

Each mappers(x) in array matches the column in the file and puts the value into the DB matching the name on the array

Eg `name, description, amount`

Puts col A value in name field 
Col B value in description field 

Once done, we will need to implement the [Quasar component to take the CSV, read and process the mapping](https://github.com/juicyllama-npm/quasar/issues/142).

**Comment by andyslack** [comment]
Fantastic work @shershen08 

1. support for different encodings of the file(screen 1), can start with only UTF-8 - **Agreed, lets remove this for now and default to UTF-8, if it becomes an issue in the future we can improve**.
2. support for various file formats ( screen 1), can start with only CSV for example - **Agreed**
3. data delimiter symbols (screen 2) - **@yossi-shasho  what do you think we can/do support out of the box on screen 2? We should keep it simple, maybe just Field Delimiter and Text Qualifier for now?**
4. ability to track upload progress in a live progress bar. Can be for now replaced with a simple indefinite loading animated element. - **Makes sense for v1 but we should submit a task for the future to improve.**

**Comment by yossi-shasho** [comment]
@andyslack we can tell the CSV library which delimiter to use. right now its unset so its using its default

**Comment by yossi-shasho** [comment]
@shershen08 sure, POST /users/upload_csv
see https://api.sentinel.hiveuw.com/#tag/Users/operation/UsersController_uploadCSVFile

**Comment by andyslack** [comment]
I want to test this end to end from frontend widget back before signoff. 

I will install it in one client project and test it fully.

**Comment by andyslack** [comment]
Hi @shershen08 

I have updated the response back from the bulk upload to give more data to the frontend:

The response now looks like:

```
{
    total: data.length,
    processed: 0,
    created: 0,
    updated: 0,
    deleted: 0,
    errored: 0,
    errors: []
 } 
```

With errors being an array of error messages. 

Do you think you can improve the "results" page of the bulk upload to reflect these new values?

**Comment by andyslack** [comment]
@shershen08 is this done yet?
