### ISSUE TITLE
ModuleRef broken DI

### ISSUE THREAD

**Issue by andyslack** [juicyllama/framework#69]
NestJS DI gets broken when https://github.com/juicyllama/client-quickstart/ is linked to the framework for local development  via
```sh
pnpm run install:client:backend
```

This is caused by multiple instances of the `@nestjs/core` package in `client-quickstart` and `framework`.

the error is:

```
Nest can't resolve dependencies of the TypeOrmCoreModule (TypeOrmModuleOptions, ?). Please make sure that the argument ModuleRef at index [1] is available in the TypeOrmCoreModule context.
```

**Comment by Yurko-Fedoriv** [comment]
The immediate fix for this (from within `client-quickstart/backend`, assuming `framework` is located in the same parent directory as `client-quickstart`):

```sh
> $ cd node_modules/@nestjs
> $ rm -rf core/
> $ ln -s ../../../../framework/node_modules/@nestjs/core
```

This is a functional workaround, but it looks dirty.
I plan to explore if instead, we can utilize `pnpm link` to reliably point `framework` and `client-quickstart` to the same instance of the `@nestjs/core`.

**Comment by andyslack** [comment]
Fixed
