### ISSUE TITLE
Redoc is not working properly

### ISSUE THREAD

**Issue by shvamabps** [juicyllama/framework#96]
![image](https://github.com/juicyllama/framework/assets/37547983/4eb8048d-56df-4f0f-b6ef-87a385438a72)

After installing the packages using `pnpm` commands mentioned in `package.json` file, I tried and visited the api url, but the redoc shows this type of error.

**Comment by shvamabps** [comment]
Any suggestions as to how to resolve this.

**Comment by andyslack** [comment]
Hi @shvamabps 

The redoc package was merged into `core` and the `nestjs-redoc` was depreciated.

`pnpm install @juicyllama/core`

Then update imports to point to this package.

**Comment by shvamabps** [comment]
Thanks @andyslack  for the update. Let me try implementing this and get back to you.

**Comment by andyslack** [comment]
Checkout the docs here also: https://docs.juicyllama.com/framework/backend/core/helpers/nestjs-redoc/readme

**Comment by shvamabps** [comment]
Is it possible to configure Swagger itself instead of redoc @andyslack  ??

**Comment by andyslack** [comment]
The swagger implementatin is handled via NestJS's Swagger package: `@nestjs/swagger`

Full documentation here: https://docs.nestjs.com/openapi/introduction
